# Generated by Django 4.1.5 on 2023-05-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postjob',
            name='Description',
        ),
        migrations.AlterField(
            model_name='postjob',
            name='Upload_Logo',
            field=models.ImageField(upload_to=None),
        ),
    ]
