# Generated by Django 4.1.5 on 2023-05-22 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsite', '0004_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contacts',
        ),
    ]
